#!/bin/sh

set -e

HEAD=$(git symbolic-ref refs/remotes/origin/HEAD)
DEFAULT_BRANCH=$(echo $HEAD | sed 's@^refs/remotes/origin/@@')

git stash save --include-untracked Autostashing

git checkout $DEFAULT_BRANCH
git fetch --all
git pull
git checkout -b $* $DEFAULT_BRANCH
