#!/bin/sh

set -e

HEAD=$(git symbolic-ref refs/remotes/origin/HEAD)
DEFAULT_BRANCH=$(echo $HEAD | sed 's@^refs/remotes/origin/@@')
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

git checkout $DEFAULT_BRANCH
git pull
git checkout $CURRENT_BRANCH
git rebase $DEFAULT_BRANCH
