#!/bin/sh

set -e

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
TITLE=$(echo $CURRENT_BRANCH | awk '{gsub(/-/, " ", $0); print toupper(substr($0, 0, 1)) substr($0, 2)}')

echo "${*:-$TITLE}" | hub pull-request -F - -dope
